# ........................................................
# Title .................. Baccarat Simulator
# Author ................. Raoul R. Diez
# Date ................... February 8, 2016
# Description ............ This Baccarat Game Simulator, generates result of an actual casino floor game
# ........................ showing cards drawn to each side respective to rules of the game. At the end
# ........................ of the simulation, it will generate data analysis giving the central tendency
# ........................ of the game, using the simulplay() function.
# ........................................................

library(plyr)
suit <- c("H", "C", "D", "S")
bottomsuit <- c("H", "C")
topsuit <- c("D", "S")
rank <- c(1:10, "J", "Q", "K")
rrank <- c("K","Q","J", 10:1)
deck <- NULL #create the deck
fdeck <- NULL
tcount <- 0 #true count based on 8 & 9 removal from the shoe to gain DRAGON advantage.



for (r in rank) {
  deck <- c(deck, paste(r, suit))
}

for (h in bottomsuit) {
  fdeck <- c(fdeck, paste(rank, h))
}
for (h in topsuit) {
  fdeck <- c(fdeck, paste(rrank, h))
}

#returns a randomly shuffled deck
shuffle <- function(deck) {
  return(sample(deck, length(deck)))
}

#draws n cards from deck starting at card start
draw_cards <- function(deck, start, n = 1) {
  cards <- NULL
  for (i in start:(start + n - 1)) {
    if (i <= length(deck)) {
      cards <- c(cards, deck[i])
    }
  }
  return(cards)
}

#

createDeck <- function(totalNumOfDecks = 2)
{
  suits <- c("Hearts", "Clubs", "Diamonds", "Spades")
  cards <- c("Ace", "Deuce", "Three", "Four","Five", 
             "Six", "Seven", "Eight", "Nine", "Ten", 
             "Jack", "Queen", "King")
  values <- c(1,2,3,4,5,
              6,7,8,9,10,
              10,10,10)
  
  deck <- data.frame(Suit=character(0), Card=character(0), Value=numeric(0))
  
  numOfDecks = 1
  
  while (numOfDecks <= totalNumOfDecks){
    for (i in suits){
      for (j in cards){
        deck <- rbind.data.frame(deck, cbind.data.frame(j, i, values[match(j, cards)]))
      }
    }
    numOfDecks = numOfDecks + 1
  }
  
  print(deck)
}


#returns a randomly shuffled deck/decks of cards

ShuffleDecks <- NULL
CardstoDeal <- NULL


dealcard <- function(s, i = TRUE) {
  
  #i is TRUE if validating only for one card (hit card)
  
  upcard <- c('J','Q','K')
  value <- 0
  
  if (substr(s[1],1,1) %in% upcard) {
    value <- 10
  }else{
    value <- as.integer(substr(s[1],1,2))
  }
  if (!i) {
    if (substr(s[2],1,1) %in% upcard) {
      value <- value + 10
    }else{
      value <- value + as.integer(substr(s[2],1,2))
    }
  }
  return(value)
}

#Generates a shuffled deck with a default value of 8 decks.

NewBaccShoe <- function(d = 8) {
  v <- 0
  tcount <- 0
  
  tcards <- NULL
  for (i in 1:d) {
    ShuffleDecks <- append(ShuffleDecks,shuffle(deck))
  }
  ShuffleDecks <- sample(ShuffleDecks,length(ShuffleDecks))
  # v = dealcard(ShuffleDecks)
  # tcards<-ShuffleDecks[1:(v+1)]
  # # for (i in 1:(v+1)){
  # #   tcount <- tcount + dealcard(tcards[i])
  # # }
  # # cal_tcount(tcount)
  # # print(tcards)
  # # print(tcount)
  # 
  # CardstoDeal <- ShuffleDecks[v + 2:length(ShuffleDecks)]
  # #print(ShuffleDecks[1])
  # cat(sprintf("Burry Card is %s \n", ShuffleDecks[1]))
  # cat(sprintf("Discarding a total of %d cards \n", v + 1))
  # return(CardstoDeal[1:(length(ShuffleDecks) - (v + 1))])
  return(ShuffleDecks)
}


# Simulate Live Game deals from start, which discards additional cards based on the first drawn card,
# until cards left in the shoe is less than 6. Argument is an array of shuffled deck generated by
# NewBaccShoe() function.

StartLiveGame <- function(s=NewBaccShoe(), dv = TRUE) {
  plyr <- NULL
  bnkr <- NULL
  mboard <- NULL
  p <- 0
  b <- 0
  d <-0
  pscore <- 0
  bscore <- 0
  board <- NULL
  spread <- 0
  pp <- 0
  bd <- 0
  dcount <- 0
  ShuffleDecks <- NULL
  tcards <- NULL
  tcount <- 0
  rcount <-0
  cnshoe <- NULL
  v<-0
  
  #Save the sequence of shuffled decks
  cnshoe <- s
  
  d <- length(s)/52
  v <- dealcard(s)
  tcards <- s[1:(v+1)]
 
   for (i in 1:(v+1)){
     if (dealcard(tcards[i]) %in% c(8,9)) {
      rcount <- (rcount + 1)
      tcount <- rcount/d
     }
   }
  
  if (dv){
    cat(sprintf("Burry Card is %s \n", s[1]))
    cat(sprintf("Discarding a total of %d cards \n", v + 1))
  }
  s <- s[(v + 2):length(s)]
  if (dv){
    cat(sprintf("The cards remaining are: %d \n",length(s)))
  }
  
  while (length(s) > 6) {
    if (length(s) < 11) {
      if (dv) {
        
        #cat("\n")
        print(matrix(board,length(board) / 3,3, byrow = TRUE))
        print(table(matrix(board,length(board) / 3,3, byrow = TRUE)[,1]))
        invisible(readline("L A S T   D E A L !!! ...."))
      }
    }
    if (dv) {
      cat(dcount <- dcount + 1,"\n")
    }
    plyr <- NULL
    bnkr <- NULL
    tcp <- FALSE
    tcb <- FALSE
    plyr <- s[c(1,3)]
    bnkr <- s[c(2,4)]
    
    for (i in 1:4){
      if (dealcard(s[i]) %in% c(8,9)) {
        rcount <- (rcount + 1)
        tcount <- rcount/d
      }
    }
    
    if (dv) {
      cat(sprintf("Player has %s and %s and ", plyr[1],plyr[2]))
      cat(sprintf("Banker has %s and %s \n", bnkr[1],bnkr[2]))
    }
    s <- s[c(5:length(s))]
    
    pscore <- dealcard(plyr,FALSE) %% 10
    bscore <- dealcard(bnkr,FALSE) %% 10
    
    if (dv) {
      cat(sprintf("Player %d and Banker %d \n", pscore, bscore))
    }
    #Validate for a natural win
    if ((pscore > 7) || (bscore > 7)) {
      #Natural Wins
      if (pscore > bscore) {
        if (dv) {
          cat(sprintf("Player Wins: Natural %d vs. %d  \n", pscore, bscore))
        }
        board <- c(board,"P",4 , tcount)
      }
      if (bscore > pscore) {
        if (dv) {
          cat(sprintf("Banker Wins: Natural %d vs. %d  \n", bscore, pscore))
        }
        board <- c(board,"B", 4, tcount)
      }
      if (bscore == pscore) {
        if (dv) {
          cat(sprintf("TIE:  %d and %d  \n", bscore, pscore))
        }
        board <- c(board,"/", 0, tcount)
      }
    }
    
    if ((pscore <= 7) && (bscore <= 7)) {
      if (pscore >= 6 && bscore < 6) {
        hcard <- dealcard(s) %% 10
        if (hcard %in% c(8,9)){
          rcount <- rcount +1
          tcount <- rcount /d
        }
        #s <- s[c(2:length(s))]
        #Banker draws third card
        tcb <- TRUE
        bscore <- (bscore + hcard) %% 10
        if (dv) {
          cat(sprintf("Banker draws %s, makes %d \n", s[1], bscore))
        }
        s <- s[c(2:length(s))]
      }
      if ((pscore < 6) && (bscore <= 7)) {
        hcard <- dealcard(s) %% 10
        
        if (hcard %in% c(8,9)){
          rcount <- rcount +1
          tcount <- rcount /d
        }
        
        #Player draws third card
        tcp <- TRUE
        pscore <- (pscore + hcard) %% 10
        if (dv) {
          cat(sprintf("Player draws %s, makes %d \n ", s[1], pscore))
        }
        s <- s[c(2:length(s))]
        
        if ((bscore == 6) && (hcard %in% c(6,7)) |
            (bscore == 5) && (hcard %in% c(4,5,6,7)) |
            (bscore == 4) && (hcard %in% c(2,3,4,5,6,7)) |
            (bscore == 3) && (hcard %in% c(1,2,3,4,5,6,7,9,0)) |
            (bscore < 3)) {
          #Banker Draws
          tcb <- TRUE
          hcard <- dealcard(s) %% 10
          
          bscore <- (bscore + hcard) %% 10
          if (dv) {
            cat(sprintf("Banker draws %s, makes %d \n", s[1], bscore))
          }
          s <- s[c(2:length(s))]
        }
      }
      
      if (pscore > bscore) {
        #Player Wins
        if (dv) {
          if (tcp && pscore == 8) {
            cat(sprintf("PANDA: %d vs %d \n", pscore, bscore))
          }else{
            cat(sprintf("Player Wins: %d vs %d \n", pscore, bscore))
          }
        }
        spread <- pscore - bscore
        ifelse(
          pscore == 8 && tcp ==
            TRUE,board <-
            c(board,"PP", spread, tcount), board <- c(board,"P", spread, tcount)
        )
        #ifelse(tcp == TRUE,cat(sprintf("PANDA!: %d vs. %d  \n", pscore, bscore)),cat(sprintf("Player Wins: %d vs %d  \n", pscore, bscore)))
      }
      if (bscore > pscore) {
        #Banker Wins
        if (dv) {
          if (tcb && bscore == 7) {
            cat(sprintf("DRAGON: %d vs %d \n", bscore, pscore))
          }else{
            cat(sprintf("Banker Wins: %d vs %d \n", bscore, pscore))
          }
        }
        spread <- bscore - pscore
        
        ifelse(
          bscore == 7 &&
            tcb == TRUE,board <-
            c(board,"BD", spread, tcount), board <- c(board,"B", spread, tcount)
        )
        #ifelse(tcb == TRUE,cat(sprintf("D-R-A-G-O-N: %d vs %d  \n", bscore, pscore)),cat(sprintf("Banker Wins: %d vs %d  \n", bscore, pscore)))
      }
      if (bscore == pscore) {
        if (dv) {
          cat(sprintf("TIE. Both are %d \n", bscore))
        }
        board <- c(board,"/", 0, tcount)
      }
    }
    #invisible(readline("...."))
  }
  if (dv){
  cat("Total Deals: ", length(board) / 3,"\n")
  print(table(matrix(board,(length(board) / 3),3, byrow = TRUE)[,1]))
  }
  mboard <- matrix(board,(length(board) / 3),3, byrow = TRUE)
  return (list(dboard=mboard, cards=cnshoe))
}

#verify number of the same cards      

VerifyCard <-
  function(NewShoe, CardtoSearch = "1 S", n = length(NewShoe)) {
    CountCards <- 0
    for (i in 1:n) {
      if (NewShoe[i] == CardtoSearch) {
        CountCards = CountCards + 1
      }
    }
    return (CountCards)
  }



#Initiates new game randomly based on first drawn card

newshoe <- function(S,n = 1) {
  CardstoDeal <- NULL
  upcard <- c('J','Q','K')
  value <- 0
  if (substr(S[n],1,1) %in% upcard) {
    value = 10
  }else{
    value = strtoi(substr(S[n],1,1))
  }
  CardstoDeal <- S[value + 2:length(S)]
  return(CardstoDeal[1:(length(S) - (value + 1))])
}



# To simulate continous games. Default value is 20 shoes.

simulplay <- function(n = 20) {
  deals <- 0
  bdcount <-0
  dcount <- NULL
  mresult <- NULL
  dresult <- NULL
  indexc <- NULL
  sresult <- NULL
  noties <- NULL
  r_nties <- NULL
  brun <- 0
  prun <- 0
  mcountv <- NULL
  mcount <- NA
  drgncount <- NULL
  dmode <- 0
  ls <- NULL
  cardsinshoe <-NULL
  mcardsinshoe <- NULL
  
  for (i in 1:n) {
    
    # Assign container for every cards dealt per shoe
    cardsbkt <- matrix(n:416)
    ls <- StartLiveGame(dv=0)
    
    # Assign the returned list[1] value equals the game result
    #liveshoe <- ldply(ls[1],data.frame)
    liveshoe <- ls$dboard
    
    
    # Assigne the second list as the undealt cards in the shoe
    # cardsinshoe <- c(cardsinshoe, unlist(ls[2]))
    cardsinshoe <- c(cardsinshoe,ls$cards)
    invisible(print(i))
  
    # Obtain the mode value of true count
    bdcount <- which(liveshoe[,1]=="BD")
    if (identical(bdcount,integer(0))==FALSE){
      ndragon <- which(liveshoe[,1]=="BD")
      drgncount <- c(drgncount,as.numeric(liveshoe[ndragon,3]))
    }
    
    # mcountv <- table(drgncount)
    
    # Obtain the mode of Dragon
    # mcount <- as.numeric(names(mcountv)[mcountv==max(mcountv)])
    
    deals <- deals + length(liveshoe[,1])
    sresult <- liveshoe[,1]
    noties <- sresult[sresult != "/"]
    r_nties <- rle(substr(noties,1,1))
    brun <- max(r_nties$lengths[r_nties$values=="B"])
    prun <- max(r_nties$lengths[r_nties$values=="P"])
    #indexc <- which(liveshoe[,1]=="BD")
    dcount <- c(dcount, c(sum(liveshoe[,1] == "BD"), sum(liveshoe[,1]=="PP"),sum(liveshoe[,1]=="/"),sum(liveshoe[,1] == "P"),sum(liveshoe[,1] == "B"), brun, prun))
  }
  mcountv <- table(drgncount)
  mcount <- as.numeric(names(mcountv)[mcountv==max(mcountv)])
  mcardsinshoe <- matrix(cardsinshoe,n,416,byrow = TRUE)
  
  cnames <- c("Dragon","Panda","Tie","Player","Banker", "BRun", "PRun")
  mresult <- matrix(dcount,n,7,1)
  colnames(mresult)<- cnames
  dresult <- data.frame(mresult)
  cat("Total Deals: ", deals, "\n")
  return(list(board=dresult,tc=drgncount,mode=mcount,cards=mcardsinshoe))
}

# Run the function below to start simulation
# The default simulation is 20 shoes/games
#
newgame <- simulplay()
# To extract values from the variable and show the result use
#
gresult <- sapply(newgame$board,summary)
# To show true count (removal of 9's and 8's in the shoe) tendencies on dragon.
# plot(table(newgame$tc))
#
# View the top bucket of cards
cstorage <- as.character(head(newgame$cards[1,]))
# Maximum Dragon outcome in a shoe
cat("Max Dragon Count in a Shoe: ", max(newgame$board$Dragon))
# Location of highest dragon count
drgnindex <- which(newgame$board$Dragon==max(newgame$board$Dragon,na.rm = TRUE))


